# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Activity(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uuid: str=None):
        """
        Activity - a model defined in Swagger

        :param uuid: The uuid of this Activity.
        :type uuid: str
        """
        self.swagger_types = {
            'uuid': str
        }

        self.attribute_map = {
            'uuid': 'uuid'
        }

        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'Activity':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Activity of this Activity.
        :rtype: Activity
        """
        return deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """
        Gets the uuid of this Activity.
        Unique identifier for the activity

        :return: The uuid of this Activity.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """
        Sets the uuid of this Activity.
        Unique identifier for the activity

        :param uuid: The uuid of this Activity.
        :type uuid: str
        """

        self._uuid = uuid

