# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Profile(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, first_name: str=None, last_name: str=None, email: str=None, picture: str=None, promo_code: str=None):
        """
        Profile - a model defined in Swagger

        :param first_name: The first_name of this Profile.
        :type first_name: str
        :param last_name: The last_name of this Profile.
        :type last_name: str
        :param email: The email of this Profile.
        :type email: str
        :param picture: The picture of this Profile.
        :type picture: str
        :param promo_code: The promo_code of this Profile.
        :type promo_code: str
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'email': str,
            'picture': str,
            'promo_code': str
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'picture': 'picture',
            'promo_code': 'promo_code'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._picture = picture
        self._promo_code = promo_code

    @classmethod
    def from_dict(cls, dikt) -> 'Profile':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profile of this Profile.
        :rtype: Profile
        """
        return deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """
        Gets the first_name of this Profile.
        First name of the Uber user.

        :return: The first_name of this Profile.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """
        Sets the first_name of this Profile.
        First name of the Uber user.

        :param first_name: The first_name of this Profile.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """
        Gets the last_name of this Profile.
        Last name of the Uber user.

        :return: The last_name of this Profile.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """
        Sets the last_name of this Profile.
        Last name of the Uber user.

        :param last_name: The last_name of this Profile.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """
        Gets the email of this Profile.
        Email address of the Uber user

        :return: The email of this Profile.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """
        Sets the email of this Profile.
        Email address of the Uber user

        :param email: The email of this Profile.
        :type email: str
        """

        self._email = email

    @property
    def picture(self) -> str:
        """
        Gets the picture of this Profile.
        Image URL of the Uber user.

        :return: The picture of this Profile.
        :rtype: str
        """
        return self._picture

    @picture.setter
    def picture(self, picture: str):
        """
        Sets the picture of this Profile.
        Image URL of the Uber user.

        :param picture: The picture of this Profile.
        :type picture: str
        """

        self._picture = picture

    @property
    def promo_code(self) -> str:
        """
        Gets the promo_code of this Profile.
        Promo code of the Uber user.

        :return: The promo_code of this Profile.
        :rtype: str
        """
        return self._promo_code

    @promo_code.setter
    def promo_code(self, promo_code: str):
        """
        Sets the promo_code of this Profile.
        Promo code of the Uber user.

        :param promo_code: The promo_code of this Profile.
        :type promo_code: str
        """

        self._promo_code = promo_code

